[package]
name = "w2t"
version = "0.1.0"
edition = "2024"
description = "A tool for converting images to transparent PNGs"
authors = ["ksk001100 <hm.pudding0715@gmail.com>"]

[dependencies]
image = "0.25.6"
seahorse = "2.2.0"
